# Generated by Django 5.0 on 2024-01-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
        ('catogry', '0003_alter_catogry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='catogry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catogry.catogry'),
        ),
    ]
