# Generated by Django 5.0 on 2024-01-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_alter_modeldevice_name_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
