# Generated by Django 5.0 on 2024-01-03 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0005_device_created_at_device_ubdate_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='file/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ubdate_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
