# Generated by Django 5.0 on 2024-01-04 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0009_alter_devicefile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('zalaf_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ubdate_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ubdate_at', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Working'), (2, 'Out of work'), (3, 'Servicing'), (4, 'Expired')], max_length=50)),
                ('type', models.CharField(choices=[(1, 'Employee'), (2, 'Servicing')], max_length=50)),
                ('is_from', models.BooleanField(default=False)),
                ('is_to', models.BooleanField(default=False)),
                ('store', models.CharField(blank=True, max_length=50, null=True)),
                ('detiles', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ubdate_at', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.device')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.employee')),
            ],
        ),
    ]
