# Generated by Django 5.0 on 2024-01-14 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0010_employee_employeedevice_historydevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historydevice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='device',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historydevice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_device', to='Item.device'),
        ),
        migrations.AlterField(
            model_name='historydevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Item.device'),
        ),
        migrations.AlterField(
            model_name='historydevice',
            name='status',
            field=models.CharField(choices=[('1', 'Working'), ('3', 'Expired'), ('4', 'borken')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historydevice',
            name='type',
            field=models.CharField(choices=[('1', 'Employee'), ('2', 'Servicing'), ('3', 'Change status')], max_length=50),
        ),
    ]
