# Generated by Django 5.0 on 2024-01-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0011_alter_historydevice_options_device_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='type_device',
            field=models.CharField(choices=[('office', 'office'), ('Personal', 'Personal')], default='Personal', max_length=50),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.departments')),
            ],
        ),
        migrations.CreateModel(
            name='DeprtDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ubdate_at', models.DateTimeField(auto_now=True, null=True)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.departments')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.device')),
                ('office', models.ManyToManyField(blank=True, null=True, to='Item.office')),
            ],
        ),
    ]
