# Generated by Django 5.0 on 2024-01-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0012_departments_device_type_device_office_deprtdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='departments',
            new_name='department',
        ),
    ]
