# Generated by Django 5.0 on 2024-01-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0013_rename_departments_office_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydevice',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.departments'),
        ),
        migrations.AlterField(
            model_name='historydevice',
            name='type',
            field=models.CharField(choices=[('1', 'Employee'), ('2', 'Servicing'), ('3', 'Change status'), ('4', 'Departments')], max_length=50),
        ),
    ]
