# Generated by Django 5.0 on 2024-01-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0014_historydevice_departments_alter_historydevice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydevice',
            name='departments',
        ),
        migrations.AddField(
            model_name='historydevice',
            name='departDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depart_device', to='Item.deprtdevice'),
        ),
        migrations.AlterField(
            model_name='deprtdevice',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deprt_device', to='Item.departments'),
        ),
        migrations.AlterField(
            model_name='deprtdevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_depart', to='Item.device'),
        ),
    ]
