# Generated by Django 5.0 on 2024-01-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0015_remove_historydevice_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedevice',
            name='employee',
            field=models.UUIDField(editable=False),
        ),
    ]
