# Generated by Django 5.0 on 2024-01-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0016_alter_employeedevice_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydevice',
            name='employee',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
