# Generated by Django 5.0 on 2024-01-17 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0018_sparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ubdate_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='title',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='Warranty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Item.devicefile'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='service_tag',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.modelsparepart'),
        ),
    ]
