# Generated by Django 5.0 on 2024-01-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0019_modelsparepart_remove_sparepart_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
