# Generated by Django 5.0 on 2024-01-17 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0020_sparepart_purchase_date_alter_sparepart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprtdevice',
            name='office',
            field=models.ManyToManyField(blank=True, null=True, related_name='deprt_device', to='Item.office'),
        ),
        migrations.AlterField(
            model_name='device',
            name='modal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='Item.modeldevice'),
        ),
        migrations.AlterField(
            model_name='device',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='Item.store'),
        ),
        migrations.AlterField(
            model_name='modeldevice',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modelsparepart',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='Item.modelsparepart'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
