# Generated by Django 5.0 on 2024-01-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0021_alter_deprtdevice_office_alter_device_modal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
