# Generated by Django 5.0 on 2024-01-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0022_device_deleted'),
        ('catogry', '0004_catogry_created_at_catogry_ubdate_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldevice',
            name='catogry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modal', to='catogry.catogry'),
        ),
        migrations.AddField(
            model_name='modeldevice',
            name='min_device',
            field=models.IntegerField(default=1, verbose_name='Minimum number of devices for alerting'),
        ),
    ]
