# Generated by Django 5.0 on 2024-01-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0023_modeldevice_catogry_modeldevice_min_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprtdevice',
            name='office',
            field=models.ManyToManyField(related_name='deprt_device', to='Item.office'),
        ),
    ]
