# Generated by Django 5.0 on 2024-01-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catogry',
            name='descripe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
