# Generated by Django 5.0 on 2024-01-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogry', '0002_catogry_descripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogry',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
