# Generated by Django 5.0 on 2024-01-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catogry', '0003_alter_catogry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catogry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='catogry',
            name='ubdate_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
